services:
  mysql:
    image: mysql:8.4
    container_name: e-approval-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2diddnjs@
      MYSQL_DATABASE: approval
      MYSQL_USER: yang1
      MYSQL_PASSWORD: 2diddnjs@
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
